### ISSUE TITLE
incorrect quote in README.md

### ISSUE THREAD

**Issue by shagu** [FelixRTU/pfQuest-classic#1]
> It is neither a "full rewite" as Shaggy said it has to be, it is more ore less an adaption to the current lua standards.

I said that with pfUI in mind, the porting of pfQuest is just boring but not a rewrite at all.

**Comment by FelixRTU** [comment]
I removed the line. Thanks for writing.
Makes me wonder if there would have been more participation in adopting the project to classic if you had said its just boring to so. Because i think pfq is in its base still superior to questie and deservers some attention.

**Comment by shagu** [comment]
> I removed the line. Thanks for writing.

Thank you :+1: 

> Makes me wonder if there would have been more participation in adopting the project to classic if you had said its just boring to so. 

There was a guy who took pfQuest and renamed it to ClassicCodex. It was no proper 'fork' and more a copy-paste where basically everything (the name, my authorship, the readme and even the license) was removed. Under the hood, it was still pfQuest with some adjustments to make it run on classic. However, all connections to where it derives from, and who wrote the code, where removed. I didn't felt like I would need to take care of any classic porting efforts anymore. 

I would have gladly taken pull-requests to also make the official pfQuest working on classic (Same as I already did multi-client support for Vanilla and TBC [It's usually just some wrapper functions, `this`/`self` scope adjustments and `CreateFrame`-template settings]). But things went into another direction. ¯\\\_(ツ)\_/¯

After I did a [pull-request](https://github.com/pgarneau/ClassicCodex/pull/4) to at least get the license back in, I was quite done with classic and under the assumption that there is now some sort of "pfQuest" for Classic and people are satisfied. At this point, I stopped following any classic related discussions.

**Comment by FelixRTU** [comment]
Claiming ownership in that way is really not a nice thing to do. I looked it up and some things like the tracker, navigation and the settings menu are missing but he wrote some new stuff here and there. It's less of a "sloppy" thing I did. Maybe he will update it in the future, but it wasn't since Feb. 2020.

Feel free to use anything I did here if you intend to continue work. I will keep this low key and won't make any major changes. If it works, ok. beyond that, I don't really care.

**Comment by shagu** [comment]
>  I looked it up and some things like the tracker, navigation and the settings menu are missing but he wrote some new stuff here and there

Yes, those things didn't exist when the project was created. Features of both addons diverged over the last two years. 

> Feel free to use anything I did here if you intend to continue work.

Thanks, but [I'm done with addons](https://github.com/shagu/pfUI/issues/1031). As of today, I only fix bugs (if there are any) but don't really work on new things. Also I don't play classic, so it doesn't make sense for me to pick stuff I can't test.
